-- BUỔI 4
-- PHẦN 1: QUẢN LÝ BÁN HÀNG
-- BAI TAP 1
-- 19.	Có bao nhiêu hóa đơn không phải của khách hàng đăng ký thành viên mua?
SELECT COUNT(*)
FROM HOADON
WHERE MAKH NOT IN (SELECT MAKH
					FROM KHACHHANG
					WHERE KHACHHANG.MAKH = HOADON.MAKH)
-- 20. Có bao nhiêu sản phẩm khác nhau được bán ra trong năm 2006.
SELECT COUNT(DISTINCT MASP)
FROM CTHD 
	INNER JOIN 
	HOADON HD ON CTHD.SOHD = HD.SOHD
WHERE YEAR(NGHD) = 2006
-- 21.	Cho biết trị giá hóa đơn cao nhất, thấp nhất là bao nhiêu?
SELECT MIN(TRIGIA) AS THAPNHAT, MAX(TRIGIA) AS CAONHAT FROM HOADON

-- 22.	Trị giá trung bình của tất cả các hóa đơn được bán ra trong năm 2006 là bao nhiêu?
SELECT AVG(TRIGIA) AS TRUNGBINH
FROM HOADON
WHERE YEAR(NGHD) = 2006

-- 23.	Tính doanh thu bán hàng trong năm 2006.
SELECT SUM(TRIGIA) AS DOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006
-- 24.	Tìm số hóa đơn có trị giá cao nhất trong năm 2006.
/* C1 */
SELECT SOHD
FROM HOADON
WHERE YEAR(NGHD) = 2006 AND TRIGIA >= ALL (SELECT TRIGIA FROM HOADON)

/* C2 */
SELECT SOHD
FROM HOADON
WHERE YEAR(NGHD) = 2006 AND TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON)
-- 25.	Tìm họ tên khách hàng đã mua hóa đơn có trị giá cao nhất trong năm 2006.
SELECT HOTEN
FROM KHACHHANG KH
INNER JOIN
	HOADON HD ON KH.MAKH = HD.MAKH
WHERE YEAR(NGHD) = 2006 AND TRIGIA >= ALL (SELECT MAX(TRIGIA) FROM HOADON)

/* C2 */
SELECT HOTEN
FROM KHACHHANG KH
INNER JOIN
	HOADON HD ON KH.MAKH = HD.MAKH
WHERE YEAR(NGHD) = 2006 AND TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON)
-- 26.	In ra danh sách 3 khách hàng (MAKH, HOTEN) có doanh số cao nhất.
SELECT TOP 3 MAKH, HOTEN
FROM KHACHHANG
ORDER BY DOANHSO DESC
-- 27.	In ra danh sách các sản phẩm (MASP, TENSP) có giá bán bằng 1 trong 3 mức giá cao nhất.
SELECT MASP, TENSP
FROM SANPHAM
WHERE GIA IN(
	SELECT DISTINCT TOP 3 GIA -- KHAC VOI SELECT TOP 3 WITH TIES
	FROM SANPHAM
	ORDER BY GIA DESC
)
-- 28.	In ra danh sách các sản phẩm (MASP, TENSP) do “Thai Lan” sản xuất có giá bằng 1 trong 3 mức giá cao nhất (của tất cả các sản phẩm).
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Thai Lan'
AND GIA IN (SELECT DISTINCT TOP 3 GIA
			FROM SANPHAM
			ORDER BY GIA DESC)

-- 29.	In ra danh sách các sản phẩm (MASP, TENSP) do “Trung Quoc” sản xuất có giá bằng 1 trong 3 mức giá cao nhất (của sản phẩm do “Trung Quoc” sản xuất).
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
AND GIA IN (SELECT DISTINCT TOP 3 GIA
			FROM SANPHAM
			WHERE NUOCSX = 'Trung Quoc'
			ORDER BY GIA DESC)
-- 30.	* In ra danh sách 3 khách hàng có doanh số cao nhất (sắp xếp theo kiểu xếp hạng).
SELECT TOP 3 MAKH, HOTEN, RANK() OVER 
(ORDER BY DOANHSO DESC) RANK_KH
FROM KHACHHANG




-- BAI TAP 3
-- 31.	Tính tổng số sản phẩm do “Trung Quoc” sản xuất.
SELECT COUNT(MASP) AS TONGSO
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'

-- 32.	Tính tổng số sản phẩm của từng nước sản xuất.
SELECT NUOCSX, COUNT(MASP) 
FROM SANPHAM
GROUP BY NUOCSX
-- 33.	Với từng nước sản xuất, tìm giá bán cao nhất, thấp nhất, trung bình của các sản phẩm.
SELECT NUOCSX, MAX(GIA) AS MAXGIA, MIN(GIA) AS MINGIA, AVG(GIA) AS AVGGIA
FROM SANPHAM 
GROUP BY NUOCSX

-- 34.	Tính doanh thu bán hàng mỗi ngày.
SELECT NGHD, SUM(TRIGIA) AS DOANHTHU
FROM HOADON
GROUP BY NGHD

-- 35.	Tính tổng số lượng của từng sản phẩm bán ra trong tháng 10/2006.
SELECT CTHD.MASP, SUM(SL) AS SOLUONG
FROM CTHD
	INNER JOIN 
	HOADON HD ON CTHD.SOHD = HD.SOHD
WHERE MONTH(NGHD) = 10 AND YEAR(NGHD) = 2006
GROUP BY CTHD.MASP

-- 36.	Tính doanh thu bán hàng của từng tháng trong năm 2006.
SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)

-- 37.	Tìm hóa đơn có mua ít nhất 4 sản phẩm khác nhau.
SELECT SOHD
FROM CTHD
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) >= 4
-- 38.	Tìm hóa đơn có mua 3 sản phẩm do “Viet Nam” sản xuất (3 sản phẩm khác nhau).
SELECT SOHD
FROM CTHD
	INNER JOIN SANPHAM SP
	ON CTHD.MASP = SP.MASP
WHERE NUOCSX = 'Viet Nam'
GROUP BY SOHD
HAVING COUNT(DISTINCT CTHD.MASP) = 3

-- 39.	Tìm khách hàng (MAKH, HOTEN) có số lần mua hàng nhiều nhất.
/* C1 */
SELECT TOP 1 WITH TIES HD.MAKH, HOTEN, COUNT(SOHD) AS SOLAN
FROM KHACHHANG KH 
	INNER JOIN HOADON HD
	ON KH.MAKH = HD.MAKH
GROUP BY HD.MAKH, HOTEN
ORDER BY COUNT(SOHD) DESC

/* C2 */
SELECT MAKH, HOTEN FROM (
	SELECT HD.MAKH, HOTEN, RANK() OVER (ORDER BY COUNT(HD.MAKH) DESC) RANK_SOLAN 
	FROM HOADON HD INNER JOIN KHACHHANG KH 
	ON HD.MAKH = KH.MAKH
	GROUP BY HD.MAKH, HOTEN
) A
WHERE RANK_SOLAN = 1
-- 40.	Tháng mấy trong năm 2006, doanh số bán hàng cao nhất ?
/* C1 */
SELECT TOP 1 MONTH(NGHD) AS THANG, SUM(DOANHSO) AS TONGDOANHSO
FROM HOADON HD
	INNER JOIN 
	KHACHHANG KH ON HD.MAKH = KH.MAKH
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY SUM(DOANHSO) DESC

/* C2 */
SELECT THANG FROM (
	SELECT MONTH(NGHD) THANG, RANK() OVER (ORDER BY SUM(TRIGIA) DESC) RANK_TRIGIA FROM HOADON
	WHERE YEAR(NGHD) = '2006' 
	GROUP BY MONTH(NGHD)
) A
WHERE RANK_TRIGIA = 1
-- 41.	Tìm sản phẩm (MASP, TENSP) có tổng số lượng bán ra thấp nhất trong năm 2006.
/* C1 */
SELECT TOP 1 CTHD.MASP, TENSP
FROM SANPHAM SP
	 INNER JOIN CTHD ON SP.MASP = CTHD.MASP
	 INNER JOIN HOADON HD ON HD.SOHD = CTHD.SOHD
WHERE YEAR(NGHD) = 2006
GROUP BY CTHD.MASP, TENSP
ORDER BY SUM(SL) ASC

/* C2 */
SELECT A.MASP, TENSP FROM (
	SELECT MASP, RANK() OVER (ORDER BY SUM(SL)) RANK_SL
	FROM CTHD CT INNER JOIN HOADON HD
	ON CT.SOHD = HD.SOHD
	WHERE YEAR(NGHD) = '2006'
	GROUP BY MASP
) A INNER JOIN SANPHAM SP
ON A.MASP = SP.MASP
WHERE RANK_SL = 1
-- 42.	*Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất.
/* C1 */
SELECT NUOCSX, MASP, TENSP
FROM (
    SELECT NUOCSX, MASP, TENSP, 
           ROW_NUMBER() OVER (PARTITION BY NUOCSX ORDER BY GIA DESC) AS RANK_GIA
    FROM SANPHAM
) SP
WHERE RANK_GIA = 1;
/* C2 */
SELECT NUOCSX, MASP, TENSP FROM (
	SELECT NUOCSX, MASP, TENSP, GIA, RANK() OVER (PARTITION BY NUOCSX ORDER BY GIA DESC) RANK_GIA FROM SANPHAM
) A 
WHERE RANK_GIA = 1
-- 43.	Tìm nước sản xuất sản xuất ít nhất 3 sản phẩm có giá bán khác nhau.
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3				

-- 44.	*Trong 10 khách hàng có doanh số cao nhất, tìm khách hàng có số lần mua hàng nhiều nhất.
SELECT MAKH, HOTEN FROM (
	SELECT TOP 10 HD.MAKH, HOTEN, DOANHSO, RANK() OVER (ORDER BY COUNT(HD.MAKH) DESC) RANK_SOLAN
	FROM HOADON HD INNER JOIN KHACHHANG KH
	ON HD.MAKH = KH.MAKH
	GROUP BY HD.MAKH, HOTEN, DOANHSO
	ORDER BY DOANHSO DESC
) A
WHERE RANK_SOLAN = 1



-- PHẦN 2: QUẢN LÝ GIÁO VỤ
-- BAI TAP 2
-- 19.	Khoa nào (mã khoa, tên khoa) được thành lập sớm nhất.
SELECT TOP 1 WITH TIES MAKHOA, TENKHOA
FROM KHOA
ORDER BY NGTLAP ASC

/* C2 */
SELECT MAKHOA, TENKHOA FROM (
	SELECT MAKHOA, TENKHOA, RANK() OVER (ORDER BY NGTLAP) RANK_NGTLAP FROM KHOA
) A
WHERE RANK_NGTLAP = 1

-- 20.	Có bao nhiêu giáo viên có học hàm là “GS” hoặc “PGS”.
SELECT HOCHAM, COUNT(MAGV) AS SL
FROM GIAOVIEN
WHERE HOCHAM = 'GS' OR HOCHAM = 'PGS'
GROUP BY HOCHAM

SELECT HOCHAM, COUNT(HOCHAM) SL FROM GIAOVIEN 
WHERE HOCHAM IN ('GS', 'PGS') 
GROUP BY HOCHAM


-- 21.	Thống kê có bao nhiêu giáo viên có học vị là “CN”, “KS”, “Ths”, “TS”, “PTS” trong mỗi khoa.
SELECT MAKHOA, HOCVI, COUNT(MAGV) AS SL 
FROM GIAOVIEN
GROUP BY MAKHOA, HOCVI
ORDER BY MAKHOA

-- 22.	Mỗi môn học thống kê số lượng học viên theo kết quả (đạt và không đạt).
SELECT MAMH, KQUA, COUNT(MAHV) AS SL
FROM KETQUATHI
GROUP BY MAMH, KQUA

SELECT MAMH, KQUA, COUNT(MAHV) SL
FROM KETQUATHI A
WHERE NOT EXISTS (
	SELECT 1 
	FROM KETQUATHI B 
	WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
)
GROUP BY MAMH, KQUA
-- 23.	Tìm giáo viên (mã giáo viên, họ tên) là giáo viên chủ nhiệm của một lớp, đồng thời dạy cho lớp đó ít nhất một môn học.
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV IN(SELECT GD.MAGV
			  FROM LOP
			  INNER JOIN GIANGDAY GD
			  ON LOP.MALOP = GD.MALOP
			  WHERE MAGV = MAGVCN)


-- 24.	Tìm họ tên lớp trưởng của lớp có sỉ số cao nhất.
SELECT HO + ' ' + TEN AS HOTEN
FROM HOCVIEN HV
	INNER JOIN LOP
	ON HV.MALOP = LOP.MALOP
WHERE MAHV = TRGLOP AND 
SISO IN (SELECT TOP 1 WITH TIES SISO
		FROM LOP
		ORDER BY SISO DESC)
-- TOP 1 WITH TIES SỬ DỤNG ORDER BY
-- KHI TRẢ VỀ NHIỀU HƠN 1 GIÁ TRỊ KHÔNG XÀI DẤU '='. SỬ DỤNG IN
			  
SELECT HO + ' ' + TEN HOTEN FROM LOP INNER JOIN HOCVIEN HV
ON LOP.TRGLOP = HV.MAHV
WHERE SISO = (
	SELECT MAX(SISO) FROM LOP
)
-- 25.	* Tìm họ tên những LOPTRG thi không đạt quá 3 môn (mỗi môn đều thi không đạt ở tất cả các lần thi).
SELECT HO + ' ' + TEN HOTEN FROM HOCVIEN
WHERE MAHV IN (
	SELECT MAHV FROM KETQUATHI A
	WHERE MAHV IN (
		SELECT TRGLOP FROM LOP
	) AND NOT EXISTS (
		SELECT 1 FROM KETQUATHI B 
		WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
	) AND KQUA = 'Khong Dat'
	GROUP BY MAHV
	HAVING COUNT(MAMH) >= 3
)
-- BAI TAP 4
-- 26.	Tìm học viên (mã học viên, họ tên) có số môn đạt điểm 9, 10 nhiều nhất.
SELECT MAHV, HO + ' ' + TEN AS HOTEN
FROM HOCVIEN
WHERE MAHV IN (SELECT TOP 1 WITH TIES KETQUATHI.MAHV
				FROM HOCVIEN
					INNER JOIN KETQUATHI
					ON HOCVIEN.MAHV = KETQUATHI.MAHV
				WHERE DIEM BETWEEN 9 AND 10
				GROUP BY KETQUATHI.MAHV
				ORDER BY COUNT(DIEM) DESC)

SELECT A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, RANK () OVER (ORDER BY COUNT(MAMH) DESC) RANK_MH FROM KETQUATHI KQ 
	WHERE DIEM BETWEEN 9 AND 10
	GROUP BY KQ.MAHV
) A INNER JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV
WHERE RANK_MH = 1


-- 27.	Trong từng lớp, tìm học viên (mã học viên, họ tên) có số môn đạt điểm 9, 10 nhiều nhất.
SELECT 
    LOP.MALOP, 
    HV.MAHV, 
    HO + ' ' + TEN AS HOTEN, 
    COUNT(KQ.DIEM) AS SL
FROM 
    LOP
    INNER JOIN HOCVIEN HV ON HV.MALOP = LOP.MALOP
    INNER JOIN KETQUATHI KQ ON KQ.MAHV = HV.MAHV
WHERE 
    DIEM BETWEEN 9 AND 10
GROUP BY 
    LOP.MALOP, HV.MAHV, HO, TEN
HAVING 
    COUNT(KQ.DIEM) = (
        SELECT MAX(SL)
        FROM (
            SELECT 
                LOP_SUB.MALOP, 
                HV_SUB.MAHV, 
                COUNT(KQ_SUB.DIEM) AS SL
            FROM 
                LOP LOP_SUB
                INNER JOIN HOCVIEN HV_SUB ON HV_SUB.MALOP = LOP_SUB.MALOP
                INNER JOIN KETQUATHI KQ_SUB ON KQ_SUB.MAHV = HV_SUB.MAHV
            WHERE 
                KQ_SUB.DIEM BETWEEN 9 AND 10
            GROUP BY 
                LOP_SUB.MALOP, HV_SUB.MAHV
        ) AS LopDiemMax
        WHERE LopDiemMax.MALOP = LOP.MALOP
    )
ORDER BY 
    LOP.MALOP, HV.MAHV;

SELECT LEFT(A.MAHV, 3) AS MALOP, A.MAHV, HO + ' ' + TEN AS HOTEN
FROM (
    SELECT 
        MAHV, 
        LEFT(MAHV, 3) AS MALOP, 
        COUNT(MAMH) AS SO_MON, 
        RANK() OVER (PARTITION BY LEFT(MAHV, 3) ORDER BY COUNT(MAMH) DESC) AS RANK_MH
    FROM KETQUATHI
    WHERE DIEM BETWEEN 9 AND 10
    GROUP BY MAHV, LEFT(MAHV, 3)
) A
INNER JOIN HOCVIEN HV 
ON A.MAHV = HV.MAHV
WHERE RANK_MH = 1
-- 28.	Trong từng học kỳ của từng năm, mỗi giáo viên phân công dạy bao nhiêu môn học,bao nhiêu lớp.
SELECT HOCKY, NAM, MAGV, COUNT(MAMH) AS SOMH, COUNT(MALOP) AS SOLOP
FROM GIANGDAY
GROUP BY HOCKY, NAM, MAGV

-- 29.	Trong từng học kỳ của từng năm, tìm giáo viên (mã giáo viên, họ tên) giảng dạy nhiều nhất.
SELECT HOCKY, NAM, A.MAGV, HOTEN FROM (
	SELECT HOCKY, NAM, MAGV, RANK() OVER (PARTITION BY HOCKY, NAM ORDER BY COUNT(MAMH) DESC) RANK_SOMH FROM GIANGDAY
	GROUP BY HOCKY, NAM, MAGV
) A INNER JOIN GIAOVIEN GV 
ON A.MAGV = GV.MAGV
WHERE RANK_SOMH = 1

-- 30.	Tìm môn học (mã môn học, tên môn học) có nhiều học viên thi không đạt (ở lần thi thứ 1) nhất.
SELECT A.MAMH, TENMH FROM (
	SELECT MAMH, RANK() OVER (ORDER BY COUNT(MAHV) DESC) RANK_SOHV FROM KETQUATHI
	WHERE LANTHI = 1 AND KQUA = 'Khong Dat'
	GROUP BY MAMH
) A INNER JOIN MONHOC MH
ON A.MAMH = MH.MAMH
WHERE RANK_SOHV = 1
-- 31.	Tìm học viên (mã học viên, họ tên) thi môn nào cũng đạt (chỉ xét lần thi thứ 1).
SELECT A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, COUNT(KQUA) SODAT FROM KETQUATHI 
	WHERE LANTHI = 1 AND KQUA = 'Dat'
	GROUP BY MAHV
	INTERSECT
	SELECT MAHV, COUNT(MAMH) SOMH FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
) A INNER JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV
-- 32.	* Tìm học viên (mã học viên, họ tên) thi môn nào cũng đạt (chỉ xét lần thi sau cùng).
SELECT C.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, COUNT(KQUA) SODAT FROM KETQUATHI A
	WHERE NOT EXISTS (
		SELECT 1 
		FROM KETQUATHI B 
		WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
	) AND KQUA = 'Dat'
	GROUP BY MAHV
	INTERSECT
	SELECT MAHV, COUNT(MAMH) SOMH FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
) C INNER JOIN HOCVIEN HV
ON C.MAHV = HV.MAHV
-- 33.	* Tìm học viên (mã học viên, họ tên) đã thi tất cả các môn và đều đạt (chỉ xét lần thi thứ 1).
SELECT A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, COUNT(KQUA) SODAT FROM KETQUATHI 
	WHERE LANTHI = 1 AND KQUA = 'Dat'
	GROUP BY MAHV
	INTERSECT
	SELECT MAHV, COUNT(MAMH) SOMH FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
) A INNER JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV
-- 34.	* Tìm học viên (mã học viên, họ tên) đã thi tất cả các môn và đều đạt (chỉ xét lần thi sau cùng).
SELECT C.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, COUNT(KQUA) SODAT FROM KETQUATHI A
	WHERE NOT EXISTS (
		SELECT 1 FROM KETQUATHI B 
		WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
	) AND KQUA = 'Dat'
	GROUP BY MAHV
	INTERSECT
	SELECT MAHV, COUNT(MAMH) SOMH FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
) C INNER JOIN HOCVIEN HV
ON C.MAHV = HV.MAHV
-- 35.	** Tìm học viên (mã học viên, họ tên) có điểm thi cao nhất trong từng môn (lấy điểm ở lần thi sau cùng).
SELECT A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT B.MAMH, MAHV, DIEM, DIEMMAX
	FROM KETQUATHI B INNER JOIN (
		SELECT MAMH, MAX(DIEM) DIEMMAX FROM KETQUATHI
		GROUP BY MAMH
	) C 
	ON B.MAMH = C.MAMH
	WHERE NOT EXISTS (
		SELECT 1 FROM KETQUATHI D 
		WHERE B.MAHV = D.MAHV AND B.MAMH = D.MAMH AND B.LANTHI < D.LANTHI
	) AND DIEM = DIEMMAX
) A INNER JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV
