USE master
--DROP DATABASE QuanLyTrongTrot
CREATE DATABASE QuanLyTrongTrot

USE QuanLyTrongTrot
--1
CREATE TABLE KHACHHANG (
	MAKH VARCHAR(4) PRIMARY KEY,
	TENKH VARCHAR(50),
	DIACHI VARCHAR(50),
	LOAIKH VARCHAR(20)
)

CREATE TABLE LOAICAY(
	MALC VARCHAR(4) PRIMARY KEY,
	TENLC VARCHAR(50),
	XUATXU VARCHAR(20),
	GIA INT
)

CREATE TABLE HOADON (
	SOHD VARCHAR(5) PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH VARCHAR(4) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	KHUYENMAI SMALLINT
)

CREATE TABLE CTHD (
	SOHD VARCHAR(5),
	MALC VARCHAR(4),
	SOLUONG SMALLINT
	CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MALC) 
)

--2
SET DATEFORMAT DMY
INSERT INTO KHACHHANG VALUES
('KH01', 'Liz Kim Cuong', 'Ha Noi', 'Vang lai'),
('KH02', 'Ivone Dieu Linh','Da Nang','Thuong xuyen'),
('KH03', 'Emma Nhat Khanh','TP.HCM','Vang lai');

INSERT INTO LOAICAY VALUES
('LC01', 'Xuong rong tai tho', 'Mexico', 180000),
('LC02', 'Sen thach ngoc', 'Anh', 300000),
('LC03', 'Ba mau rau','Nam Phi',270000);

INSERT INTO HOADON VALUES
('00001', '22/11/2017', 'KH01', 5),
('00002', '04/12/2017', 'KH03', 5),
('00003', '10/12/2017', 'KH02', 10);

INSERT INTO CTHD VALUES
('00001', 'LC01', 1),
('00001', 'LC02', 2),
('00003', 'LC03', 5);

--3.Hiện thực ràng buộc toàn vẹn sau: Tất cả các mặt hàng xuất xứ từ nước Anh đều có giá lớn hơn 250.000đ (1đ).
ALTER TABLE LOAICAY
ADD CONSTRAINT CHK CHECK (
	NOT(
		GIA<=250000 AND XUATXU = 'Anh'
	)
)

GO 
CREATE TRIGGER TRG_GIA_XUATXU ON LOAICAY
AFTER INSERT, UPDATE
AS
BEGIN
	DECLARE @XUATXU VARCHAR(20), @GIA INT;

	SELECT @GIA = GIA, @XUATXU = XUATXU
	FROM inserted;

	IF (@XUATXU = 'Anh' AND @GIA <= 250000)
	BEGIN 
		RAISERROR('LOI: GIA KHONG HOP LE!', 16, 1)
		ROLLBACK TRAN
	END
	ELSE 
	BEGIN
		PRINT N'THANH CONG'
	END
END

--4.Hiện thực ràng buộc toàn vẹn sau: Hóa đơn mua với số lượng tổng cộng lớn hơn hoặc bằng 5 đều được giảm giá 10 phần trăm. (2đ).
GO
CREATE TRIGGER TRG_GIAMGIA ON HOADON
AFTER INSERT, UPDATE 
AS
BEGIN
	IF EXISTS(
		SELECT I.MAKH
		FROM inserted I INNER JOIN CTHD CT
		ON I.SOHD = CT.SOHD
		WHERE I.KHUYENMAI <> 10
		GROUP BY I.MAKH
		HAVING SUM(CT.SOLUONG) >= 5

	)
	BEGIN
		ROLLBACK TRAN
		PRINT N'KHUYEN MAI PHAI LA 10 NEU TONG SL SAN PHAM LON HON 5'
	END
	ELSE
	BEGIN
		PRINT N'THANH CONG'
	END
END

--5.Tìm tất cả các hóa đơn có ngày lập hóa đơn trong quý 4 năm 2017, sắp xếp kết quả tăng dần theo phần trăm giảm giá (1đ).
SELECT HD.SOHD
FROM HOADON HD
WHERE MONTH(NGHD) >= 10 AND YEAR(NGHD) = 2017
ORDER BY KHUYENMAI DESC

--6.Tìm loại cây có số lượng mua ít nhất trong tháng 12 (1đ).
SELECT TOP 1 WITH TIES LC.MALC, SOLUONG
FROM LOAICAY LC INNER JOIN CTHD CT
ON LC.MALC = CT.MALC
INNER JOIN HOADON HD
ON CT.SOHD = HD.SOHD
WHERE MONTH(HD.NGHD) = 12
ORDER BY CT.SOLUONG ASC

--7.Tìm loại cây mà cả khách thường xuyên (LOAIKH là ‘Thuong xuyen’) và khách vãng lai (LOAIKH là ‘Vang lai’) đều mua. (1đ).
SELECT LC.MALC
FROM LOAICAY LC INNER JOIN CTHD CT
ON LC.MALC = CT.MALC
INNER JOIN HOADON HD
ON CT.SOHD = HD.SOHD
INNER JOIN KHACHHANG KH
ON HD.MAKH = HD.MAKH
WHERE KH.LOAIKH = 'Vang lai'
INTERSECT
	SELECT LC.MALC
	FROM LOAICAY LC INNER JOIN CTHD CT
	ON LC.MALC = CT.MALC
	INNER JOIN HOADON HD
	ON CT.SOHD = HD.SOHD
	INNER JOIN KHACHHANG KH
	ON HD.MAKH = HD.MAKH
	WHERE KH.LOAIKH = 'Thuong xuyen'

--8.Tìm khách hàng đã từng mua tất cả các loại cây (1đ).
SELECT * 
FROM KHACHHANG KH
WHERE NOT EXISTS (
	SELECT *
	FROM LOAICAY LC
	WHERE NOT EXISTS (
		SELECT * 
		FROM HOADON HD INNER JOIN CTHD CT 
		ON HD.SOHD = CT.SOHD
		WHERE HD.MAKH = KH.MAKH AND CT.MALC = LC.MALC
	)
)